export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const GET_PROJECTS_LOADING = 'GET_PROJECTS_LOADING';

export const GET_VOYAGES = 'GET_VOYAGES';
export const GET_VOYAGES_ERROR = 'GET_VOYAGES_ERROR';
export const GET_VOYAGES_LOADING = 'GET_VOYAGES_LOADING';
export const LOADING_GET_VOYAGES = 'LOADING_GET_VOYAGES';

export const LOADING_DELETE_VOYAGE = 'LOADING_DELETE_VOYAGE';
export const DELETE_VOYAGE = 'DELETE_VOYAGE';
export const ERROR_DELETE_VOYAGE = 'ERROR_DELETE_VOYAGE';

export const GET_SINGLE_VOYAGE = 'GET_SINGLE_VOYAGE';
export const GET_SINGLE_VOYAGE_ERROR = 'GET_SINGLE_VOYAGE_ERROR';
export const GET_SINGLE_VOYAGE_LOADING = 'GET_SINGLE_VOYAGE_LOADING';

export const EDIT_VOYAGE = 'EDIT_VOYAGE';
export const EDIT_VOYAGE_LOADING = 'EDIT_VOYAGE_LOADING';
export const EDIT_VOYAGE_ERROR = 'EDIT_VOYAGE_ERROR';

export const ADD_TEAM = 'ADD_TEAM';
export const ADD_TEAM_LOADING = 'ADD_TEAM_LOADING';
export const ADD_TEAM_ERROR = 'ADD_TEAM_ERROR';

export const GET_TEAM = 'GET_TEAM';
export const GET_TEAM_LOADING = 'GET_TEAM_LOADING';
export const GET_TEAM_ERROR = 'GET_TEAM_ERROR';

export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_LOADING = 'GET_ALL_TEAMS_LOADING';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';

export const UPDATE_TEAM = 'UPDATE_TEAM';
export const UPDATE_TEAM_LOADING = 'UPDATE_TEAM_LOADING';
export const UPDATE_TEAM_ERROR = 'UPDATE_TEAM_ERROR';

export const DELETE_TEAM = 'DELETE_TEAM';
export const DELETE_TEAM_LOADING = 'DELETE_TEAM_LOADING';
export const DELETE_TEAM_ERROR = 'DELETE_TEAM_ERROR';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_LOADING = 'CREATE_TEAM_LOADING';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';

export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';
export const GET_SINGLE_PROJECT_ERROR = 'GET_SINGLE_PROJECT_ERROR';
export const GET_SINGLE_PROJECT_LOADING = 'GET_SINGLE_PROJECT_LOADING';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const UPDATE_PROJECT_LOADING = 'UPDATE_PROJECT_LOADING';

export const ADD_SPRINT = 'ADD_SPRINT';
export const ADD_SPRINT_LOADING = 'ADD_SPRINT_LOADING';
export const ADD_SPRINT_ERROR = 'ADD_SPRINT_ERROR';

export const EDIT_SPRINTS = 'EDIT_SPRINTS';
export const EDIT_SPRINTS_LOADING = 'EDIT_SPRINTS_LOADING';
export const EDIT_SPRINTS_ERROR = 'EDIT_SPRINTS_ERROR';

export const ADD_TICKET="ADD_TICKET";
export const ADD_TICKET_LOADING="ADD_TICKET_LOADING";
export const ADD_TICKET_ERROR="ADD_TICKET_ERROR";